version: "3.2"

volumes:
  esdata01:
    driver: local

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - "ELASTIC_PASSWORD=changeme"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elk
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "-u", "http://elastic:9200/_cat/health"]
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    container_name: kibana
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    environment:
      - SERVER_NAME=kibana.local
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk
  logstash:
    image: docker.elastic.co/logstash/logstash:7.7.0
    container_name: logstash
    volumes:
      - type: bind
        source: ./logstash/pipeline/logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf
        read_only: true
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
    ports:
    - "5044:5044/tcp"
    - "5044:5044/udp"
    - "9600:9600"
    environment:
      - "LS_JAVA_OPTS: -Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    networks:
      - elk
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.7.0
    container_name: filebeat
    user: root
    volumes:
      - type: volume
        source: ./monitors/filebeat/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml:ro
      - type: volume
        source: /var/lib/docker
        target: /var/lib/docker:ro
      - type: volume
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    restart: unless-stopped
    depends_on:
      - logstash
    networks:
      - elk
networks:
  elk:
    driver: bridge


