filebeat:
  image: docker.elastic.co/beats/filebeat:7.7.0
  container_name: filebeat
  volumes:
    - type: volume
      source: ./filebeat/filebeat.yml
      target: /usr/share/filebeat/filebeat.yml
  restart: unless-stopped
  depends_on:
    - logstash
  networks:
    - elk
